package com.uob.frtb.risk.samr.model;

public enum RiskClassAndSensitivity {

	IR_DELTA, IR_VEGA, IR_CURVATURE, IR_INFLATION, IR_BASIS,
	FX_DELTA, FX_VEGA, FX_CURVATURE, 
	EQ_DELTA, EQ_VEGA, EQ_CURVATURE, 
	CR_NS_DELTA, CR_NS_VEGA, CR_NS_CURVATURE, 
	CR_SEC_NON_CTP_DELTA, CR_SEC_CTP_DELTA, 
	COMM_DELTA, COMM_VEGA, COMM_CRUVATURE,
	DRC_NON_SEC, DRC_SEC_NON_CTP, DRC_SEC_CTP,
    RESIDUALS
}
